import prisma from "./prisma";
import type { Prisma } from "@prisma/client";

/**
 * 审计日志操作类型常量
 * 覆盖需求 16.1 中定义的所有敏感操作
 */
export const AuditAction = {
  // 用户管理
  ROLE_CHANGE: "ROLE_CHANGE",
  USER_BAN: "USER_BAN",
  USER_UNBAN: "USER_UNBAN",
  SHADOW_BAN: "SHADOW_BAN",

  // 内容审核
  CONTENT_APPROVE: "CONTENT_APPROVE",
  CONTENT_REJECT: "CONTENT_REJECT",
  POST_REVISION_SUBMIT: "POST_REVISION_SUBMIT",
  POST_REVISION_APPROVE: "POST_REVISION_APPROVE",
  POST_REVISION_REJECT: "POST_REVISION_REJECT",
  ADMIN_POST_CORRECT: "ADMIN_POST_CORRECT",
  ADMIN_PROFILE_CORRECT: "ADMIN_PROFILE_CORRECT",
  PHONE_EMERGENCY_CHANGE: "PHONE_EMERGENCY_CHANGE",
  PASSWORD_RESET: "PASSWORD_RESET",

  // 举报处理
  REPORT_RESOLVE: "REPORT_RESOLVE",
  REPORT_DISMISS: "REPORT_DISMISS",
  REPORT_CLAIM: "REPORT_CLAIM",
  REPORT_ACTION_APPLY: "REPORT_ACTION_APPLY",

  // DCR 区
  DCR_ACCESS_GRANT: "DCR_ACCESS_GRANT",
  DCR_ACCESS_REVOKE: "DCR_ACCESS_REVOKE",
  CASE_EXPORT: "CASE_EXPORT",
  CASE_ACCESS: "CASE_ACCESS",
  CREATE_CASE: "CREATE_CASE",
  SUPPLEMENT_CASE: "SUPPLEMENT_CASE",
  REVIEW_CASE: "REVIEW_CASE",
  UPDATE_CASE_STATUS: "UPDATE_CASE_STATUS",
  CREATE_TASK: "CREATE_TASK",
  PUBLISH_TASK_FROM_APPROVED_CASE: "PUBLISH_TASK_FROM_APPROVED_CASE",
  TASK_SUBMIT: "TASK_SUBMIT",
  TASK_REVIEW: "TASK_REVIEW",
  TASK_APPROVE: "TASK_APPROVE",
  TASK_REJECT: "TASK_REJECT",
  TASK_CLAIM_REQUEST: "TASK_CLAIM_REQUEST",
  TASK_CLAIM_ACCEPT: "TASK_CLAIM_ACCEPT",
  TASK_CLAIM_REJECT: "TASK_CLAIM_REJECT",
  TASK_START: "TASK_START",
  TASK_CLOSE_REQUEST: "TASK_CLOSE_REQUEST",
  TASK_CLOSE_CONFIRM: "TASK_CLOSE_CONFIRM",
  TASK_COMPLETE: "TASK_COMPLETE",
  TASK_FORCE_CLOSE: "TASK_FORCE_CLOSE",
  TASK_DISPUTE: "TASK_DISPUTE",
  VIEW_EVIDENCE: "VIEW_EVIDENCE",
  CREATE_EVIDENCE: "CREATE_EVIDENCE",
  DOWNLOAD_EVIDENCE: "DOWNLOAD_EVIDENCE",
  EXPORT_EVIDENCE: "EXPORT_EVIDENCE",
  DISPUTE_TAKEDOWN: "DISPUTE_TAKEDOWN",
  DISPUTE_REPLACE_HELPER: "DISPUTE_REPLACE_HELPER",
  DISPUTE_BAN_USER: "DISPUTE_BAN_USER",
  DISPUTE_DISMISS: "DISPUTE_DISMISS",
  DISPUTE_FREEZE: "DISPUTE_FREEZE",

  // 板块权限
  BOARD_PERMISSION_CHANGE: "BOARD_PERMISSION_CHANGE",

  // 心理区
  PSYCH_ACCESS_GRANT: "PSYCH_ACCESS_GRANT",
  PSYCH_ACCESS_REJECT: "PSYCH_ACCESS_REJECT",
  PSYCH_ACCESS_APPLY: "PSYCH_ACCESS_APPLY",
  CONFIDE_CREATE: "CONFIDE_CREATE",
  CONFIDE_CLOSE: "CONFIDE_CLOSE",
  PSYCH_MATCH_CLAIM: "PSYCH_MATCH_CLAIM",

  // 知识库
  KB_ARTICLE_CREATE: "KB_ARTICLE_CREATE",

  // 群聊治理
  CHAT_MEMBER_KICK: "CHAT_MEMBER_KICK",
  CHAT_MEMBER_BAN: "CHAT_MEMBER_BAN",
  CHAT_MEMBER_UNBAN: "CHAT_MEMBER_UNBAN",

  // 邀请码
  INVITE_CREATE: "INVITE_CREATE",
  INVITE_REVOKE: "INVITE_REVOKE",

  // 超级管理员
  SUPER_ADMIN_OVERRIDE: "SUPER_ADMIN_OVERRIDE",

  // 系统
  SYSTEM_RESTART: "SYSTEM_RESTART",
  SYSTEM_CONFIG_UPDATE: "SYSTEM_CONFIG_UPDATE",
  SITE_CONTENT_UPDATE: "SITE_CONTENT_UPDATE",
  ANNOUNCEMENT_CREATE: "ANNOUNCEMENT_CREATE",
  ANNOUNCEMENT_UPDATE: "ANNOUNCEMENT_UPDATE",
  ANNOUNCEMENT_BROADCAST: "ANNOUNCEMENT_BROADCAST",
  POST_PIN_UPDATE: "POST_PIN_UPDATE",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  AI_REVIEW_REQUEST: "AI_REVIEW_REQUEST",
  AI_REVIEW_COMPLETE: "AI_REVIEW_COMPLETE",
  AI_REVIEW_FAILED: "AI_REVIEW_FAILED",
  AI_REVIEW_BLOCKED: "AI_REVIEW_BLOCKED",
  AI_CONFIG_UPDATE: "AI_CONFIG_UPDATE",
  QQ_MESSAGE_CONTENT_VIEW: "QQ_MESSAGE_CONTENT_VIEW",
  QQ_BOT_OPERATION_REQUEST: "QQ_BOT_OPERATION_REQUEST",
  QQ_BOT_CREDENTIAL_VIEW: "QQ_BOT_CREDENTIAL_VIEW",
  QQ_OFFICIAL_BOT_CONNECTION_TEST: "QQ_OFFICIAL_BOT_CONNECTION_TEST",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

/**
 * 审计日志目标对象类型常量
 */
export const AuditTargetType = {
  USER: "USER",
  POST: "POST",
  COMMENT: "COMMENT",
  REPORT: "REPORT",
  CASE: "CASE",
  BOARD: "BOARD",
  INVITE_CODE: "INVITE_CODE",
  APPLICATION: "APPLICATION",
  ACCESS_APPLICATION: "ACCESS_APPLICATION",
  CONFIDE_REQUEST: "CONFIDE_REQUEST",
  KNOWLEDGE_ARTICLE: "KNOWLEDGE_ARTICLE",
  CHAT_ROOM: "CHAT_ROOM",
  TASK: "TASK",
  EVIDENCE_ROOM: "EVIDENCE_ROOM",
  EVIDENCE_ITEM: "EVIDENCE_ITEM",
  SYSTEM: "SYSTEM",
  QQ_MESSAGE: "QQ_MESSAGE",
  ANNOUNCEMENT: "ANNOUNCEMENT",
} as const;

export type AuditTargetTypeValue =
  (typeof AuditTargetType)[keyof typeof AuditTargetType];

/**
 * 记录审计日志（仅 INSERT，不可修改、不可删除）
 *
 * @param operatorId - 操作者用户 ID
 * @param action - 操作类型
 * @param targetType - 目标对象类型
 * @param targetId - 目标对象 ID
 * @param details - 操作详情（可选）
 * @param ipHash - IP 地址哈希（可选）
 * @returns 创建的审计日志记录
 *
 * Validates: Requirements 16.1, 16.2, 16.3
 */
export async function logAudit(
  operatorId: string,
  action: string,
  targetType: string,
  targetId: string,
  details?: Prisma.InputJsonValue,
  ipHash?: string,
  client: Pick<Prisma.TransactionClient, "auditLog"> = prisma,
) {
  return client.auditLog.create({
    data: {
      operatorId,
      action,
      targetType,
      targetId,
      details: details ?? undefined,
      ipHash: ipHash ?? undefined,
    },
  });
}
