// Generated by scripts/generate-git-history.mjs. Do not edit manually.
export const GIT_HISTORY_SOURCE_COMMIT = "218c81c7d58834a83b9d794b49518cfe5be0c1d4";
export const GIT_HISTORY = [
  {
    "hash": "43445edba70e9648f0b1373b45ff73a8e220b495",
    "shortHash": "43445ed",
    "committedAt": "2026-03-02T21:59:48+08:00",
    "authorName": "zhangli091011",
    "subject": "fix some bugs",
    "type": "other",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "0f180dd11f73020695bd0a855f03a6c440c82c85",
    "shortHash": "0f180dd",
    "committedAt": "2026-03-02T22:02:34+08:00",
    "authorName": "zhangli091011",
    "subject": "Delete .kiro/specs directory",
    "type": "other",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "de36b4509e8f1e907a50ff31012c5cb1462dbe42",
    "shortHash": "de36b45",
    "committedAt": "2026-06-28T07:10:22+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: DCR审核状态机重构 + trustLevel体系 + 通用私信 + 首页品牌化",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "18d05a2bcca27d3241f2c710039d33dcea0e83b1",
    "shortHash": "18d05a2",
    "committedAt": "2026-07-02T23:45:05+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: Dockerfile改用npm ci + node:22-alpine修复部署构建失败",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d27ff102d5b4445c4e3e099e83a0eb3e1e1dd107",
    "shortHash": "d27ff10",
    "committedAt": "2026-07-03T00:04:32+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: NEXTAUTH_URL改为环境变量引用，避免生产环境跳转localhost",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "55fa8c0eeb4bb0c17a281ca2ce065a1c73f8c19d",
    "shortHash": "55fa8c0",
    "committedAt": "2026-07-03T00:15:28+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: NEXTAUTH_URL强制要求设置，移除localhost默认fallback",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "91e58fb39c5a3c808e922f999714494a2be0fece",
    "shortHash": "91e58fb",
    "committedAt": "2026-07-12T00:24:51+08:00",
    "authorName": "zhangli091011",
    "subject": "ci: add automatic production deployment",
    "type": "ci",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "74f8d500c3f1577120c94c5047bfcf05940913f6",
    "shortHash": "74f8d50",
    "committedAt": "2026-07-12T00:29:55+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: create deployment archive outside workspace",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "4fc7f65701891873a2fbbaaadfb21077bb36f633",
    "shortHash": "4fc7f65",
    "committedAt": "2026-07-12T00:34:45+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: pin negotiated SSH host fingerprint",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d34d964c8a471c49b98884da87b99adec8d0ddf9",
    "shortHash": "d34d964",
    "committedAt": "2026-07-12T00:39:48+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: deploy with pinned OpenSSH host keys",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "170fe6f1589f28960978fd3f3ce03aca7e03c95a",
    "shortHash": "170fe6f",
    "committedAt": "2026-07-12T01:18:50+08:00",
    "authorName": "zhangli091011",
    "subject": "test: 修复因DCR审核状态机+trustLevel变更导致的46个测试失败，降至仅6个预存失败",
    "type": "test",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d092e6faf508b60e8619ef33bdb07951411b6286",
    "shortHash": "d092e6f",
    "committedAt": "2026-07-12T01:22:15+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 修复 dcr-page.test.ts 的 no-assign-module-variable ESLint 错误",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "b1a78d63a1c9eb7e92d975a9ac5e8a688d8ecf58",
    "shortHash": "b1a78d6",
    "committedAt": "2026-07-12T01:29:13+08:00",
    "authorName": "zhangli091011",
    "subject": "test: 修复所有测试失败(boards/navigation/auth)，降至仅5个预存property-test",
    "type": "test",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "5db8022cb0a496f2cfbcb2a16f283eb43c61b388",
    "shortHash": "5db8022",
    "committedAt": "2026-07-12T01:53:08+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: NextAuth build error - externalize nodemailer/bcryptjs + dynamic route",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "4cf556689de173d4a0e2f722dd49d9507d330e55",
    "shortHash": "4cf5566",
    "committedAt": "2026-07-12T02:51:00+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 修复全流程分析发现的28个问题(P0-P4)",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "eb413051b60228994fa8054869291a44d94dcbca",
    "shortHash": "eb41305",
    "committedAt": "2026-07-12T11:57:48+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 页面底部显示版本号 + GitHub Actions自动递增 (v0.2.0起)",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "32be0ed00c92d7f31fa84aa58748d4dda9b27610",
    "shortHash": "32be0ed",
    "committedAt": "2026-07-12T11:59:30+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 修复 bump-version workflow run-name 无效引用",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "827bc1fa075e3eff3e75153e43f90e1ce980a536",
    "shortHash": "827bc1f",
    "committedAt": "2026-07-12T03:59:41Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.1",
    "type": "build",
    "version": "0.2.1",
    "isMerge": false
  },
  {
    "hash": "08f1a9e8d4b7ca0ac426e97e8bddc8cecbbb7d34",
    "shortHash": "08f1a9e",
    "committedAt": "2026-07-12T12:53:43+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 超级管理员系统运行日志查看功能",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "5a9a2d28e10f5c1fa96c377e32a13eb9a9916076",
    "shortHash": "5a9a2d2",
    "committedAt": "2026-07-12T04:53:53Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.2",
    "type": "build",
    "version": "0.2.2",
    "isMerge": false
  },
  {
    "hash": "1d12ae98ca300962367d5ac0067c4f7ffd436606",
    "shortHash": "1d12ae9",
    "committedAt": "2026-07-12T14:08:34+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 注册后自动登录 + 绑定手机号后JWT同步 + middleware DB回退防死循环",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "7f60f5bdc69d8574b9d88c5bdf4fe2cc6b19b56a",
    "shortHash": "7f60f5b",
    "committedAt": "2026-07-12T06:08:47Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.3",
    "type": "build",
    "version": "0.2.3",
    "isMerge": false
  },
  {
    "hash": "050bade49fbf95a2347413d2b750ef05d71ee408",
    "shortHash": "050bade",
    "committedAt": "2026-07-12T14:21:24+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 修复手机号绑定死循环 - middleware用token.id替补token.sub + bindphone页面session检测提前跳转",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "62166e40387a1d6cb83121cfc413b9abbd7bf0e4",
    "shortHash": "62166e4",
    "committedAt": "2026-07-12T06:21:38Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.4",
    "type": "build",
    "version": "0.2.4",
    "isMerge": false
  },
  {
    "hash": "ef3d7da1a806714fc3d9f4ff3708c8ac88b29135",
    "shortHash": "ef3d7da",
    "committedAt": "2026-07-12T14:49:25+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR委托表全流程闭环——提交后展示审核结果+缺项补交入口+委托表列表可操作",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "518458abc18d29142fbbcfaa2a1f9594a770c801",
    "shortHash": "518458a",
    "committedAt": "2026-07-12T06:49:36Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.5",
    "type": "build",
    "version": "0.2.5",
    "isMerge": false
  },
  {
    "hash": "0eed7fef9418b8d2001670fb63cbc2fa43804081",
    "shortHash": "0eed7fe",
    "committedAt": "2026-07-12T15:03:02+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: onboarding完成跳转死循环+upload 500+dcr/requests Suspense边界",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ca50f551405f8fc07cf645e9e0c1aae8fd2587c9",
    "shortHash": "ca50f55",
    "committedAt": "2026-07-12T07:03:14Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.6",
    "type": "build",
    "version": "0.2.6",
    "isMerge": false
  },
  {
    "hash": "d2ec1a689e77b1705ebf9654ccdc2ca1fa3ae8b0",
    "shortHash": "d2ec1a6",
    "committedAt": "2026-07-12T15:14:40+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: DCR流程对齐实际业务—四步流程(提交→审核→考核→交流)+考核入口改APPROVED+自动授予dcrAccess",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "977fba83e9c210cfaa1c2e0c0ca1f7a97066a92a",
    "shortHash": "977fba8",
    "committedAt": "2026-07-12T15:20:36+08:00",
    "authorName": "zhangli091011",
    "subject": "Merge branch 'main' of github.com:Downs-Crying-for-Rights/student-community-platform",
    "type": "merge",
    "version": null,
    "isMerge": true
  },
  {
    "hash": "36860928cd89406bd2acb3c9f0ad7b646df719c7",
    "shortHash": "3686092",
    "committedAt": "2026-07-12T15:30:03+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 多校检测阈值 3→5 修复正常委托表提交被误判驳回",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "4f613ab15d1b604bc987e855905cf03e71d56b9d",
    "shortHash": "4f613ab",
    "committedAt": "2026-07-12T07:30:20Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.7",
    "type": "build",
    "version": "0.2.7",
    "isMerge": false
  },
  {
    "hash": "8d782e3722876bd94ca4e9896e66bb42167775d5",
    "shortHash": "8d782e3",
    "committedAt": "2026-07-12T17:23:56+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 三方互助循环 A→B→C→A 完整功能 + 23项测试全通过 + 迁移完成",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "917ef49dbc415a896ca9e611d3435368bf035e81",
    "shortHash": "917ef49",
    "committedAt": "2026-07-12T09:24:07Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.8",
    "type": "build",
    "version": "0.2.8",
    "isMerge": false
  },
  {
    "hash": "980decb47fdebfd33c237a3a356bdcef5c11119e",
    "shortHash": "980decb",
    "committedAt": "2026-07-12T17:33:11+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: P0-互助任务CLAIMED→IN_PROGRESS+scope=mine+case审核分支可达; P1-权限分离+举报联动+错误提示+CTA修复",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "9a64c7b197f039024fe8725986c3c31e764197ff",
    "shortHash": "9a64c7b",
    "committedAt": "2026-07-12T09:33:21Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.9",
    "type": "build",
    "version": "0.2.9",
    "isMerge": false
  },
  {
    "hash": "38db6258924781eb8c4d7df702bf34e90225af2d",
    "shortHash": "38db625",
    "committedAt": "2026-07-12T17:45:34+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: DCR入口门控—无dcrAccess跳转入频测试+题库管理后台+3步流程+DB试题库",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "10618c5c45c7aedffa7ea1935e003218026228de",
    "shortHash": "10618c5",
    "committedAt": "2026-07-12T09:45:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.10",
    "type": "build",
    "version": "0.2.10",
    "isMerge": false
  },
  {
    "hash": "df9fd1218ad52b40f58540453c96349d0a0645db",
    "shortHash": "df9fd12",
    "committedAt": "2026-07-12T17:55:10+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 系统日志console拦截 + 修复dcr/page.tsx JSX语法错误",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "80de4257b79cec1bda839fd5621eefd7d5f4cfca",
    "shortHash": "80de425",
    "committedAt": "2026-07-12T09:55:29Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.11",
    "type": "build",
    "version": "0.2.11",
    "isMerge": false
  },
  {
    "hash": "ab2ba4e2a0d1d4b78ca812e851096c5a612b6261",
    "shortHash": "ab2ba4e",
    "committedAt": "2026-07-12T18:15:29+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: dcr/page.tsx 缺失 useRouter import 致构建失败",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "0dbd8c337f664d844abd8fc1f404e60d8f2670dd",
    "shortHash": "0dbd8c3",
    "committedAt": "2026-07-12T10:16:12Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.12",
    "type": "build",
    "version": "0.2.12",
    "isMerge": false
  },
  {
    "hash": "31d625e842f9535de61eb3fa2b82288f5ba45ba2",
    "shortHash": "31d625e",
    "committedAt": "2026-07-12T18:41:01+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 类IM群聊功能(ChatRoom/ChatRoomMember/ChatMessage)",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "8b7c93591409308180513bcadd2ba59f90fda626",
    "shortHash": "8b7c935",
    "committedAt": "2026-07-12T10:41:18Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.13",
    "type": "build",
    "version": "0.2.13",
    "isMerge": false
  },
  {
    "hash": "fea5c33707e78507702e6a573fefd504291f6438",
    "shortHash": "fea5c33",
    "committedAt": "2026-07-12T19:20:11+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 群聊页面添加TopBar/Sidebar/BottomNav导航栏 + 创建群聊需审核",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c6c399d7a09b73c49b2e304587451b9a08f7fc0d",
    "shortHash": "c6c399d",
    "committedAt": "2026-07-12T11:20:27Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.14",
    "type": "build",
    "version": "0.2.14",
    "isMerge": false
  },
  {
    "hash": "7daebc2bab16eb562ca939dd4e006b36a0d949d5",
    "shortHash": "7daebc2",
    "committedAt": "2026-07-12T19:37:40+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 公开群OWNER可选择审核加入(ChatRoomJoinRequest)",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ea1b47c23541bf37e2b3f5cd8d6d276fef4545ff",
    "shortHash": "ea1b47c",
    "committedAt": "2026-07-12T19:37:40+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: instrumentation.ts使用共享prisma实例避免生产数据库连接失败",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "34d00cda4efc135cc308eef0c520157a112b2fa3",
    "shortHash": "34d00cd",
    "committedAt": "2026-07-12T11:37:54Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.15",
    "type": "build",
    "version": "0.2.15",
    "isMerge": false
  },
  {
    "hash": "554675aadb4d1284f0b4cd6a2231eea97898b52c",
    "shortHash": "554675a",
    "committedAt": "2026-07-12T19:49:51+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 添加缺失的 newJoinMode useState 声明",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ff270de30df2e82aaea0925e4f57f68590a9fff6",
    "shortHash": "ff270de",
    "committedAt": "2026-07-12T11:50:07Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.16",
    "type": "build",
    "version": "0.2.16",
    "isMerge": false
  },
  {
    "hash": "1d58e43ba73c04b07f13f1703e54d4673a3ac3d7",
    "shortHash": "1d58e43",
    "committedAt": "2026-07-12T20:42:04+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 注册强制用户名+个人主页过滤+群聊导航+发布按钮居中",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "51e6b63f0d6dd2507daf96066c409c90d7210ce6",
    "shortHash": "51e6b63",
    "committedAt": "2026-07-12T21:04:40+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 强制无昵称用户设置用户名—中间件拦截+/set-username页+/api/auth/username+修复注册nickname未解构",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c4c89f070d28da8e1e60f83ae0de2e958f2e36e1",
    "shortHash": "c4c89f0",
    "committedAt": "2026-07-12T22:02:15+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 系统性修复37个问题 — 功能/界面/安全/性能/可维护性全面优化",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "86cf4cadb87d5ab2713506bf4dbf47e62726f5ef",
    "shortHash": "86cf4ca",
    "committedAt": "2026-07-12T14:03:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.16",
    "type": "build",
    "version": "0.2.16",
    "isMerge": false
  },
  {
    "hash": "81e505609aa7ecbc15d5bf9433188b9fe137dffc",
    "shortHash": "81e5056",
    "committedAt": "2026-07-12T22:09:36+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: chat/page.tsx 补充缺失的 Link 导入",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "6b384c81d99d23aa2ef4eafa25b77689d57dfb83",
    "shortHash": "6b384c8",
    "committedAt": "2026-07-12T14:09:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.17",
    "type": "build",
    "version": "0.2.17",
    "isMerge": false
  },
  {
    "hash": "95eb4573be267e210ab50292abad0233ba3e33c5",
    "shortHash": "95eb457",
    "committedAt": "2026-07-12T22:14:18+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: disputes路由newStatus类型改为TaskStatus枚举",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "8ebd55d673573565484b089e937e16d9be743882",
    "shortHash": "8ebd55d",
    "committedAt": "2026-07-12T14:14:54Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.18",
    "type": "build",
    "version": "0.2.18",
    "isMerge": false
  },
  {
    "hash": "62f1a8247e3c007725ad63bad1472d85ce59311d",
    "shortHash": "62f1a82",
    "committedAt": "2026-07-12T22:29:36+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 10个文件字符串字面量改为Prisma枚举值(CaseStatus/TaskStatus/PostStatus等)",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "4f733353f57b6e7502f464fa90531113f833588a",
    "shortHash": "4f73335",
    "committedAt": "2026-07-12T14:29:52Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.19",
    "type": "build",
    "version": "0.2.19",
    "isMerge": false
  },
  {
    "hash": "4d1dd5a53ab4c67037e49aa2944fcfc6b3045624",
    "shortHash": "4d1dd5a",
    "committedAt": "2026-07-12T22:36:08+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: override路由logAudit详情参数类型断言为Prisma.InputJsonValue",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ba9e75fde87bd4fc5f19a1840e32400a6568c3c5",
    "shortHash": "ba9e75f",
    "committedAt": "2026-07-12T14:36:20Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.20",
    "type": "build",
    "version": "0.2.20",
    "isMerge": false
  },
  {
    "hash": "7546eca1bf73d3b73117124ac906426fd91a224c",
    "shortHash": "7546eca",
    "committedAt": "2026-07-12T22:44:03+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 修复enum/rate-limit/auth/trust-level等多处类型错误，恢复ignoreBuildErrors(预存问题)",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "90dd9eea7b24314d7812e64b5bcf5883dcb6c4b6",
    "shortHash": "90dd9ee",
    "committedAt": "2026-07-12T14:44:20Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.21",
    "type": "build",
    "version": "0.2.21",
    "isMerge": false
  },
  {
    "hash": "54d4af2e7daa7623715ef35cf7b343cc6695e30d",
    "shortHash": "54d4af2",
    "committedAt": "2026-07-13T09:15:04+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 移除CSRF中间件(反向代理后host不匹配)+修复rate-limiter调用方式",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ddfc30fbc3d7d2f2a85e471480a20a660bf7fa22",
    "shortHash": "ddfc30f",
    "committedAt": "2026-07-13T01:15:17Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.22",
    "type": "build",
    "version": "0.2.22",
    "isMerge": false
  },
  {
    "hash": "a6b178fde81b5f6ee1b677438cdec654aad54332",
    "shortHash": "a6b178f",
    "committedAt": "2026-07-13T10:34:58+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR/心理区页面添加统一PageShell导航壳(TopBar+Sidebar+BottomNav)",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "49c2c9295f3d7e56e150b83f2f4d23b4f6e660e6",
    "shortHash": "49c2c92",
    "committedAt": "2026-07-13T10:47:49+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 中间件强制昵称检查提升为第1优先级，未设用户名重定向到/set-username；matcher覆盖所有页面路由",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "cc355813b885dda021e793cef5a1e2f10ff8bcf2",
    "shortHash": "cc35581",
    "committedAt": "2026-07-13T02:48:22Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.23",
    "type": "build",
    "version": "0.2.23",
    "isMerge": false
  },
  {
    "hash": "40f73598248087cbb47a6774a23e86916af29482",
    "shortHash": "40f7359",
    "committedAt": "2026-07-13T11:05:50+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 创建缺失的select组件(群聊页面崩溃根因); 日志页保持admin layout导航",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c780b6cf1245a819a617a051476313bc37d4a63d",
    "shortHash": "c780b6c",
    "committedAt": "2026-07-13T11:05:50+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: middleware改为纯JWT检测(移除Prisma DB查询)兼容Edge Runtime",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "40ea94ec24b0af35924f916bfd5c9daeb3dcac66",
    "shortHash": "40ea94e",
    "committedAt": "2026-07-13T03:06:06Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.24",
    "type": "build",
    "version": "0.2.24",
    "isMerge": false
  },
  {
    "hash": "7589435f4d6ca600feb4bb6ba6acde704b695518",
    "shortHash": "7589435",
    "committedAt": "2026-07-13T11:11:01+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 中间件添加SystemLog记录-页面访问/重定向事件写入DB; 修复系统日志永远为空",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "bbd7119a51a7fe39f8f595d8c0502d811aeeef20",
    "shortHash": "bbd7119",
    "committedAt": "2026-07-13T03:11:14Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.25",
    "type": "build",
    "version": "0.2.25",
    "isMerge": false
  },
  {
    "hash": "bd228f90d62798336bc673d6f05a48dfdd1d07fd",
    "shortHash": "bd228f9",
    "committedAt": "2026-07-13T11:35:03+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 启用instrumentationHook使console拦截器实际生效 — 所有console.log/error/warn自动写入SystemLog",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "31da7e68ccdf9d590b7a6297331f64649402342a",
    "shortHash": "31da7e6",
    "committedAt": "2026-07-13T03:35:14Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.26",
    "type": "build",
    "version": "0.2.26",
    "isMerge": false
  },
  {
    "hash": "04b3521f916717ca74f0f34d93550ff161d736fb",
    "shortHash": "04b3521",
    "committedAt": "2026-07-13T13:16:13+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: CSP恢复unsafe-eval — Next.js构建管道和React Fast Refresh均需要eval",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "5304e5e295ea287eab731c1a762b03d4b2312b03",
    "shortHash": "5304e5e",
    "committedAt": "2026-07-13T13:16:13+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: middleware中pathname声明移到使用前，删除重复声明",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a75276281da7c6dc9a35ac4c0a500b639857c1ab",
    "shortHash": "a752762",
    "committedAt": "2026-07-13T13:16:13+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: CSP开发环境保留unsafe-eval(React Fast Refresh需要); 生产移除",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "29aba302a98ba753db372334c6813b79d76364cb",
    "shortHash": "29aba30",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: pass OSS configuration to web container",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "6728d80ab6c81a2241a3f95e1ebe0fb3d74ab1d6",
    "shortHash": "6728d80",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 新手引导/设置用户名完成后用window.location硬刷新 — 避免router.push读到旧cookie导致中间件重定向",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "8011a1fbdcd20b8effdcca3b0f54d08751ecf145",
    "shortHash": "8011a1f",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "ci: verify production OSS runtime configuration",
    "type": "ci",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "caa47a163279b12a1cf6ed430d99f091a8f6373e",
    "shortHash": "caa47a1",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 中间件移除所有Prisma/Redis调用 — 纯JWT检测兼容Edge Runtime; 根除Edge Runtime报错",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d75d3d654b106712eca9a872c8972b08efbf246b",
    "shortHash": "d75d3d6",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: session.update()放入独立try-catch避免失败阻塞导航; 清理中间件未使用uid变量",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "dc5f3ea7fd2e8102db90ea1345f15c68915fcba2",
    "shortHash": "dc5f3ea",
    "committedAt": "2026-07-13T13:16:14+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: proxy private OSS images through signed media URLs",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "f7beca94c6293b64d3cc2d947dd3f6f7302402ba",
    "shortHash": "f7beca9",
    "committedAt": "2026-07-13T05:17:04Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.27",
    "type": "build",
    "version": "0.2.27",
    "isMerge": false
  },
  {
    "hash": "81d4f32552c2fd81542e73571476dc0a6a5c8690",
    "shortHash": "81d4f32",
    "committedAt": "2026-07-13T13:21:00+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: posts API补充authorId/bookmarkedBy/likedBy URL参数解析 — 修复个人主页显示全部帖子",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "23e17f6589b27a9ff833f160bf44aa35949d803e",
    "shortHash": "23e17f6",
    "committedAt": "2026-07-13T05:21:15Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.28",
    "type": "build",
    "version": "0.2.28",
    "isMerge": false
  },
  {
    "hash": "0b71e4ab3bee22789db6c1e9e9c5c291d4755961",
    "shortHash": "0b71e4a",
    "committedAt": "2026-07-13T13:27:16+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR入频流程改为考核→自动提交申请→管理员审核; 去除7日注册限制; 审批不再升DCR_HELPER",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "7bb2e67eeed75c7b37708242e4c9b5e1763f5a0b",
    "shortHash": "7bb2e67",
    "committedAt": "2026-07-13T05:27:32Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.29",
    "type": "build",
    "version": "0.2.29",
    "isMerge": false
  },
  {
    "hash": "1adeee1b3719ed5a3aca8a544b2172edf7847606",
    "shortHash": "1adeee1",
    "committedAt": "2026-07-13T13:49:04+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: BottomNav重构为三栏布局 — 左右flex+中置固定宽度, 消除图标叠加",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a7c7db4d25df0f621e15abafa8cc19c23fd9db45",
    "shortHash": "a7c7db4",
    "committedAt": "2026-07-13T13:49:04+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 测试模式verifyCode直接接受888888无需Redis — 修复本地无Redis时无法登录",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "4cbac968c6aa1a5aabf98255e00659bd0dff475d",
    "shortHash": "4cbac96",
    "committedAt": "2026-07-13T05:49:19Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.30",
    "type": "build",
    "version": "0.2.30",
    "isMerge": false
  },
  {
    "hash": "c1f9d07ec09f9b7ea94cc3d6dbb59f3b4e21f5c2",
    "shortHash": "c1f9d07",
    "committedAt": "2026-07-13T14:01:43+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 收藏/点赞标签闪烁 — useEffect用useRef防重复fetch, 移除导致循环的状态依赖",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "26477ba2dfb211e7f3b031ce4fcb37da646932d0",
    "shortHash": "26477ba",
    "committedAt": "2026-07-13T06:02:03Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.31",
    "type": "build",
    "version": "0.2.31",
    "isMerge": false
  },
  {
    "hash": "a24ee614f74852df307be6a6aa8af24b711d262c",
    "shortHash": "a24ee61",
    "committedAt": "2026-07-13T14:07:50+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 群聊API允许查看自己创建的待审批房间+joinMode schema修复; 群聊UI重构(固定底栏+管理弹窗)",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "7c1ebdde8be30429584ed97470cdf700f9200089",
    "shortHash": "7c1ebdd",
    "committedAt": "2026-07-13T06:08:07Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.32",
    "type": "build",
    "version": "0.2.32",
    "isMerge": false
  },
  {
    "hash": "5a3ddbeb56d5d439ea893f3e17dd9ed4c0b614e4",
    "shortHash": "5a3ddbe",
    "committedAt": "2026-07-13T14:18:21+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 群聊智能滚动+分页加载(上翻历史)+未读红点+免打扰+底部导航栏",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "42123986c0eb7207f419d7ce776a737d7cd18e81",
    "shortHash": "4212398",
    "committedAt": "2026-07-13T06:18:47Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.33",
    "type": "build",
    "version": "0.2.33",
    "isMerge": false
  },
  {
    "hash": "66315fe33071a3e71e0412e9b709f06393b28c51",
    "shortHash": "66315fe",
    "committedAt": "2026-07-13T14:51:16+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 底部导航重新排序—消息移至发布前使左右各3项均匀分布; 侧边栏同步",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "6bd7b261d1b5ba00a5d5f0cbbe6b540d2ef74553",
    "shortHash": "6bd7b26",
    "committedAt": "2026-07-13T06:51:31Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.34",
    "type": "build",
    "version": "0.2.34",
    "isMerge": false
  },
  {
    "hash": "c66716792c8f5c6fabfb941f3c93f360e5d2883f",
    "shortHash": "c667167",
    "committedAt": "2026-07-13T15:18:14+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 删除注册/邀请API速率限制",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ac4dd744857756ec31d7ceb5e96bbf1129e68d36",
    "shortHash": "ac4dd74",
    "committedAt": "2026-07-13T07:18:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.35",
    "type": "build",
    "version": "0.2.35",
    "isMerge": false
  },
  {
    "hash": "18622965465ba34cb224118ddaee80fd6efe09e0",
    "shortHash": "1862296",
    "committedAt": "2026-07-13T16:04:56+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: repair registration and magic link authentication",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "3c96ecbc9099c2990d8089e61a67efd1438585c5",
    "shortHash": "3c96ecb",
    "committedAt": "2026-07-13T08:05:18Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.36",
    "type": "build",
    "version": "0.2.36",
    "isMerge": false
  },
  {
    "hash": "50f36c9bc820221aec361bb39291a4fa19afb764",
    "shortHash": "50f36c9",
    "committedAt": "2026-07-13T18:59:26+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 导航三连修—手机端BottomNav增加DCR入口+聊天室桌面端加Sidebar+5个DCR页面加PageShell",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "004adee2f48978b240b5710a9805c923888ac024",
    "shortHash": "004adee",
    "committedAt": "2026-07-13T10:59:39Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.37",
    "type": "build",
    "version": "0.2.37",
    "isMerge": false
  },
  {
    "hash": "1663c8c5cace9357223bea9d00d5e8a26e2be3e9",
    "shortHash": "1663c8c",
    "committedAt": "2026-07-13T20:43:07+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add force cache refresh and service restart",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "95e2d782e5560a160b0ca1247f8877565a8c2ead",
    "shortHash": "95e2d78",
    "committedAt": "2026-07-13T12:43:34Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.38",
    "type": "build",
    "version": "0.2.38",
    "isMerge": false
  },
  {
    "hash": "d830514bbbb75f1de928f657ac9db5539e898867",
    "shortHash": "d830514",
    "committedAt": "2026-07-13T21:24:12+08:00",
    "authorName": "zhangli091011",
    "subject": "refactor: 统一MemberShell导航壳—所有会员页自动获得TopBar+Sidebar+BottomNav; BottomNav固定5位+更多菜单收拢DCR/群聊/管理等入口",
    "type": "refactor",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "faed48243f9d96e98809b162a9003696e2edcfa4",
    "shortHash": "faed482",
    "committedAt": "2026-07-13T13:24:37Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.39",
    "type": "build",
    "version": "0.2.39",
    "isMerge": false
  },
  {
    "hash": "85aab4a0f92f229ee9e105d98eeb2067421515c0",
    "shortHash": "85aab4a",
    "committedAt": "2026-07-13T22:09:04+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 清理全部TypeScript编译错误—38个源码/测试类型修复，tsc零错误",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d4dd74306aefd634c53fb2df57356a61ad503fbb",
    "shortHash": "d4dd743",
    "committedAt": "2026-07-13T14:09:29Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.40",
    "type": "build",
    "version": "0.2.40",
    "isMerge": false
  },
  {
    "hash": "8b35c530cb7188973abd12184841a85f43a1253f",
    "shortHash": "8b35c53",
    "committedAt": "2026-07-13T22:44:39+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: unify navigation and restore chat entry",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a70eb17d484eb31e423208471cafdbdf57f7e3c5",
    "shortHash": "a70eb17",
    "committedAt": "2026-07-13T14:45:04Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.41",
    "type": "build",
    "version": "0.2.41",
    "isMerge": false
  },
  {
    "hash": "63d670e5961ad121a83a44308139efd589daff6f",
    "shortHash": "63d670e",
    "committedAt": "2026-07-13T23:04:24+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: render navigation consistently on every page",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "6cb1330823fef6dcf5823b4db9e4507300a59718",
    "shortHash": "6cb1330",
    "committedAt": "2026-07-13T15:04:42Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.42",
    "type": "build",
    "version": "0.2.42",
    "isMerge": false
  },
  {
    "hash": "89006814a58098658b3cc10f8a4eaa1c6db63f4d",
    "shortHash": "8900681",
    "committedAt": "2026-07-14T00:42:23+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: complete chat navigation and room review flow",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "094fb2798a0ba7c509ce28a3edcbccc4595a4b8f",
    "shortHash": "094fb27",
    "committedAt": "2026-07-13T16:42:43Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.43",
    "type": "build",
    "version": "0.2.43",
    "isMerge": false
  },
  {
    "hash": "f9ce043b6b266dd98c1af91a643219726eb63e59",
    "shortHash": "f9ce043",
    "committedAt": "2026-07-14T23:59:03+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add live admin server console",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "e7282e0a93630107b0c819e69a2696a06b961e3d",
    "shortHash": "e7282e0",
    "committedAt": "2026-07-15T00:07:45+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: prevent stale navigation across deployments",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d211c60a048313d61eb8e957395accf9afba5df1",
    "shortHash": "d211c60",
    "committedAt": "2026-07-14T16:07:58Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.45",
    "type": "build",
    "version": "0.2.45",
    "isMerge": false
  },
  {
    "hash": "dc9623abd0b665f7d741903a31b7e17afe29d28b",
    "shortHash": "dc9623a",
    "committedAt": "2026-07-15T00:21:51+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add privacy-safe application telemetry",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "dd69a820afeae86f442d51ab986b8b162056dbdb",
    "shortHash": "dd69a82",
    "committedAt": "2026-07-15T00:29:26+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: trust forwarded host for telemetry origin",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "74fa265f49c71fabbd669955d17edbf11906f7af",
    "shortHash": "74fa265",
    "committedAt": "2026-07-15T01:48:55+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add full telemetry diagnostics",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "3c6e226c4c4b5a3905ab0fca68a9060a7b257cec",
    "shortHash": "3c6e226",
    "committedAt": "2026-07-15T02:02:15+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: DCR专区完善 — 独立教程管理+独立题库(多选)+申请状态查询+驳回原因展示+Admin后台",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "3f8eacb3fd6fc1b7d0a6b698a6d896cd26d0c76e",
    "shortHash": "3f8eacb",
    "committedAt": "2026-07-14T18:03:03Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.49",
    "type": "build",
    "version": "0.2.49",
    "isMerge": false
  },
  {
    "hash": "4f30aecc7f1deb14ccec67f88bd968094a292d67",
    "shortHash": "4f30aec",
    "committedAt": "2026-07-15T02:37:44+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: quiz页已通过时跳转回/dcr入口而非显示错误",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "db9989e11368fc351642bc9aec8a885ce4d11915",
    "shortHash": "db9989e",
    "committedAt": "2026-07-14T18:37:56Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.50",
    "type": "build",
    "version": "0.2.50",
    "isMerge": false
  },
  {
    "hash": "99ac711458e4a31d9432863b5c34c5353c3a478e",
    "shortHash": "99ac711",
    "committedAt": "2026-07-15T02:47:23+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR quiz使用dcrAccess/申请状态判断而非通用quizPassed — 修复新手题目与DCR题目冲突",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "544982414e5dd57919a49c484da76746427bc7df",
    "shortHash": "5449824",
    "committedAt": "2026-07-14T18:47:36Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.51",
    "type": "build",
    "version": "0.2.51",
    "isMerge": false
  },
  {
    "hash": "4a2a87bb388a76c8ab4a1ad1f0d983e45f27b22b",
    "shortHash": "4a2a87b",
    "committedAt": "2026-07-15T03:26:47+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR流程串联 — 考核→委托表→审核; 入口页三联状态+进度条展示; POST /api/cases自动创建AccessApplication",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ec433bf10a6ab3e946aa9ed60331143abc65975a",
    "shortHash": "ec433bf",
    "committedAt": "2026-07-14T19:26:56Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.52",
    "type": "build",
    "version": "0.2.52",
    "isMerge": false
  },
  {
    "hash": "dc91a545c0a6cf892b5995ae14ce7a1caa5884a5",
    "shortHash": "dc91a54",
    "committedAt": "2026-07-15T03:32:01+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR quiz 200+completed替代409; admin quiz校验空选项; 避免遥测显示错误码",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "0c6fd171f72c3dad2e0b3d61cc806d02664f095d",
    "shortHash": "0c6fd17",
    "committedAt": "2026-07-14T19:32:11Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.53",
    "type": "build",
    "version": "0.2.53",
    "isMerge": false
  },
  {
    "hash": "e8a819174ee2f41c1b606cd0b0e1d49f1ff6427c",
    "shortHash": "e8a8191",
    "committedAt": "2026-07-15T09:28:34+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 注册用户协议 — SiteContent模型+Admin编辑(支持Markdown)+注册页勾选弹窗",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a4c48e52400eb0fba6e4fd64e8f4210af0d0dfdf",
    "shortHash": "a4c48e5",
    "committedAt": "2026-07-15T01:28:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.54",
    "type": "build",
    "version": "0.2.54",
    "isMerge": false
  },
  {
    "hash": "1c0fe4b064d5258be928b0ea79779280849ed936",
    "shortHash": "1c0fe4b",
    "committedAt": "2026-07-15T09:44:27+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 站点内容管理支持多文档 — 动态新建/删除+列表API",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "6556314f69cc43b2705fe573b931640664b7fafe",
    "shortHash": "6556314",
    "committedAt": "2026-07-15T01:44:53Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.55",
    "type": "build",
    "version": "0.2.55",
    "isMerge": false
  },
  {
    "hash": "cee91f7da71b0b33c94e997b320d9f5335e2d9cc",
    "shortHash": "cee91f7",
    "committedAt": "2026-07-15T09:52:48+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 后台管理平台新手指引题库",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "289de305b4e6345e9d9a790a6012dd060febf694",
    "shortHash": "289de30",
    "committedAt": "2026-07-15T01:53:04Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.56",
    "type": "build",
    "version": "0.2.56",
    "isMerge": false
  },
  {
    "hash": "f85dbdad4e85a40c79c099fbf89aeb00b59c7f80",
    "shortHash": "f85dbda",
    "committedAt": "2026-07-15T10:03:33+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 注册页同时显示所有站点文档 — 公开列表API+逐条勾选+弹窗查看",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "31385cc239656de817ee005225343baaa0ffc789",
    "shortHash": "31385cc",
    "committedAt": "2026-07-15T02:03:54Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.57",
    "type": "build",
    "version": "0.2.57",
    "isMerge": false
  },
  {
    "hash": "a50ec737504531c8ee656f3bbbcc196b054e1520",
    "shortHash": "a50ec73",
    "committedAt": "2026-07-15T10:16:29+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: DCR委托改为管理员审核后公开",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "79b1298b6612d360b440dcabc8d0dd06e45674eb",
    "shortHash": "79b1298",
    "committedAt": "2026-07-15T02:16:45Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.58",
    "type": "build",
    "version": "0.2.58",
    "isMerge": false
  },
  {
    "hash": "126af26e32edaf005823c8e2a464b19008cdf3fe",
    "shortHash": "126af26",
    "committedAt": "2026-07-15T10:55:29+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 补齐委托审核入口和DCR已过审状态",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "03b4de313a44736fe712792cab7dc6530963d2cc",
    "shortHash": "03b4de3",
    "committedAt": "2026-07-15T02:55:41Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.59",
    "type": "build",
    "version": "0.2.59",
    "isMerge": false
  },
  {
    "hash": "5c94a3d49d6ab130059b1e514eb0b10ca6af6135",
    "shortHash": "5c94a3d",
    "committedAt": "2026-07-15T11:19:24+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 完善审核通知和管理后台入口",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "651616e47c6142bdaa0322aba524af465a518a55",
    "shortHash": "651616e",
    "committedAt": "2026-07-15T03:20:04Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.60",
    "type": "build",
    "version": "0.2.60",
    "isMerge": false
  },
  {
    "hash": "19c08c43911ee7e3cd274167958dd206c720fba0",
    "shortHash": "19c08c4",
    "committedAt": "2026-07-15T11:56:28+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 扩展DCR工单互助与多媒体回复",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "50f84534d1b7ec0afcab80de8403a6fc3baf81f1",
    "shortHash": "50f8453",
    "committedAt": "2026-07-15T03:56:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.61",
    "type": "build",
    "version": "0.2.61",
    "isMerge": false
  },
  {
    "hash": "9a3cc08fc955acd0ee0b7197e51e9c1b4b14c4f2",
    "shortHash": "9a3cc08",
    "committedAt": "2026-07-15T12:17:32+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: 完善DCR互助匹配与接口遥测",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "397788a6074f49e562450962c10922831a559cc0",
    "shortHash": "397788a",
    "committedAt": "2026-07-15T04:17:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.62",
    "type": "build",
    "version": "0.2.62",
    "isMerge": false
  },
  {
    "hash": "a60f68bd107d5ccce80730ffaf8c2db61c6ca3a5",
    "shortHash": "a60f68b",
    "committedAt": "2026-07-15T13:23:02+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 支持点击头像进入用户主页",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "f0b863076793c1d5ecd49bfcaac3ef942ea384cd",
    "shortHash": "f0b8630",
    "committedAt": "2026-07-15T05:23:14Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.63",
    "type": "build",
    "version": "0.2.63",
    "isMerge": false
  },
  {
    "hash": "b0c47b1a8060d45fdc5a7804ab64bb7e1541b8ae",
    "shortHash": "b0c47b1",
    "committedAt": "2026-07-18T00:00:34+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 收紧 DCR 准入并完善群聊治理",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "7cc3c89aed1e1c3f8a7292ba4658ac167fe30a7d",
    "shortHash": "7cc3c89",
    "committedAt": "2026-07-17T16:00:53Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.64",
    "type": "build",
    "version": "0.2.64",
    "isMerge": false
  },
  {
    "hash": "b460a4a097ebab6e5ba327b565b96606a614e8a4",
    "shortHash": "b460a4a",
    "committedAt": "2026-07-18T13:40:56+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: 统一 DCR 委托并完善互助循环分配",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "3a6b2de46cf61dab8d6d62f86e2fd3f04d1593c9",
    "shortHash": "3a6b2de",
    "committedAt": "2026-07-18T05:41:15Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.65",
    "type": "build",
    "version": "0.2.65",
    "isMerge": false
  },
  {
    "hash": "6dced125cd011cd3321ab5befa13e2a4cadb7a98",
    "shortHash": "6dced12",
    "committedAt": "2026-07-18T14:11:55+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: reuse approved delegation for task publishing",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "afbc26e0f3200d13698d86ecc2e8a23912aa47b6",
    "shortHash": "afbc26e",
    "committedAt": "2026-07-18T06:12:26Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.66",
    "type": "build",
    "version": "0.2.66",
    "isMerge": false
  },
  {
    "hash": "44718bcd451248da49e8051e9c375c11d5f41345",
    "shortHash": "44718bc",
    "committedAt": "2026-07-18T16:00:20+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: support multi-party mutual aid and private messages",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "2cc664687f5c4b8352de223b992ebe18e141bc43",
    "shortHash": "2cc6646",
    "committedAt": "2026-07-18T08:00:39Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.67",
    "type": "build",
    "version": "0.2.67",
    "isMerge": false
  },
  {
    "hash": "cc3472275b3d6f71e986efa9ddbe8d01ad9a372a",
    "shortHash": "cc34722",
    "committedAt": "2026-07-18T16:21:28+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: surface mutual aid claim errors in the UI",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "e19e44b9c290481fe6e3c45913dcf2ff87a24054",
    "shortHash": "e19e44b",
    "committedAt": "2026-07-18T08:21:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.68",
    "type": "build",
    "version": "0.2.68",
    "isMerge": false
  },
  {
    "hash": "b1bff07ecf3ad6c209c6ad759202d50d7bfd7259",
    "shortHash": "b1bff07",
    "committedAt": "2026-07-18T17:03:40+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add good Samaritan aid and automatic DCR admission",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "8b5b690ec1fefacdccdd8f1719533097f3465153",
    "shortHash": "8b5b690",
    "committedAt": "2026-07-18T09:04:09Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.69",
    "type": "build",
    "version": "0.2.69",
    "isMerge": false
  },
  {
    "hash": "0f3489ddac6c1c56582eaf1fbc59f50fe2f9dc52",
    "shortHash": "0f3489d",
    "committedAt": "2026-07-18T17:38:48+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: secure psychology zone posts and access flow",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "943c70a3ea7400364b6b48d30efa605e98a54f44",
    "shortHash": "943c70a",
    "committedAt": "2026-07-18T09:39:07Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.70",
    "type": "build",
    "version": "0.2.70",
    "isMerge": false
  },
  {
    "hash": "86ef3a0ecfaf7681996b18b15e7278498e8211f5",
    "shortHash": "86ef3a0",
    "committedAt": "2026-07-18T19:05:01+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add evidence attachment uploads",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "bb9b90497b17a997607c53319ac7057c298f6ad6",
    "shortHash": "bb9b904",
    "committedAt": "2026-07-18T11:05:37Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.71",
    "type": "build",
    "version": "0.2.71",
    "isMerge": false
  },
  {
    "hash": "32e82f3423195c317a76e665fc3f1f4c793937a1",
    "shortHash": "32e82f3",
    "committedAt": "2026-07-18T22:18:13+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: harden mutual aid workflows and reporting",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "d8e24c89135f8fdf26cd1ce8ab9d00bd438217f2",
    "shortHash": "d8e24c8",
    "committedAt": "2026-07-18T14:19:02Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.72",
    "type": "build",
    "version": "0.2.72",
    "isMerge": false
  },
  {
    "hash": "70a1bdb4ecad62989f9cfb7096aed6a7594e0e52",
    "shortHash": "70a1bdb",
    "committedAt": "2026-07-18T22:38:42+08:00",
    "authorName": "zhangli091011",
    "subject": "test: include report admin navigation",
    "type": "test",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "1b9f5ec2998a3185db429369f1735ff28f82da3d",
    "shortHash": "1b9f5ec",
    "committedAt": "2026-07-18T14:38:55Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.73",
    "type": "build",
    "version": "0.2.73",
    "isMerge": false
  },
  {
    "hash": "d696e56415a173894fe0f30cded1ac6df9245307",
    "shortHash": "d696e56",
    "committedAt": "2026-07-18T23:15:08+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add admin punishment history and remove reputation",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "2b06eb9dc02e87f5af94d3a5642379694fe18af4",
    "shortHash": "2b06eb9",
    "committedAt": "2026-07-18T15:15:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.74",
    "type": "build",
    "version": "0.2.74",
    "isMerge": false
  },
  {
    "hash": "d2734d6d1b8a0c016bf1175a68bc693931993c4b",
    "shortHash": "d2734d6",
    "committedAt": "2026-07-18T23:58:38+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: expand admin user and post editing",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "72dc1e65db78acf907fceb32779e8e3268bf59ae",
    "shortHash": "72dc1e6",
    "committedAt": "2026-07-18T15:59:12Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.75",
    "type": "build",
    "version": "0.2.75",
    "isMerge": false
  },
  {
    "hash": "25d64dd82db28ed746b8a37ddf3aad8652e44b4c",
    "shortHash": "25d64dd",
    "committedAt": "2026-07-19T00:39:25+08:00",
    "authorName": "zhangli091011",
    "subject": "refactor: move moderation into admin routes",
    "type": "refactor",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "f8d1af84bc283896ea67c0bc7044679908d0a7fb",
    "shortHash": "f8d1af8",
    "committedAt": "2026-07-18T16:39:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.76",
    "type": "build",
    "version": "0.2.76",
    "isMerge": false
  },
  {
    "hash": "aa36c594af92a92d88d837f3960fcb8cdf016a4b",
    "shortHash": "aa36c59",
    "committedAt": "2026-07-19T00:41:07+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: harden moderation and account security",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "09ff65b4633d1fc443529e8ab1c50dd235c7a73e",
    "shortHash": "09ff65b",
    "committedAt": "2026-07-18T16:41:30Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.77",
    "type": "build",
    "version": "0.2.77",
    "isMerge": false
  },
  {
    "hash": "a7dc2227cf41b56315540e5c269edec16408f5c2",
    "shortHash": "a7dc222",
    "committedAt": "2026-07-19T00:50:07+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: finalize report resolution workflows",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "991d64ac4bffb127ae13527118f6c7d0ab6b9472",
    "shortHash": "991d64a",
    "committedAt": "2026-07-18T16:50:57Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.78",
    "type": "build",
    "version": "0.2.78",
    "isMerge": false
  },
  {
    "hash": "1f74f11466f8cf8d64e2a04bb8678af20e3a4b5f",
    "shortHash": "1f74f11",
    "committedAt": "2026-07-19T09:23:52+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add AI review and admin alerts",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "e5019c8e559c9cb38dbe38665731e0fbe06da013",
    "shortHash": "e5019c8",
    "committedAt": "2026-07-19T01:24:12Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.79",
    "type": "build",
    "version": "0.2.79",
    "isMerge": false
  },
  {
    "hash": "95e09b0995baf2bae6960ac8afc8a8c538275b42",
    "shortHash": "95e09b0",
    "committedAt": "2026-07-19T11:02:07+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add secure QQ bot delegation flow",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "39cf2eea6af0359669aaae84848617330d5f4ce1",
    "shortHash": "39cf2ee",
    "committedAt": "2026-07-19T03:03:08Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.80",
    "type": "build",
    "version": "0.2.80",
    "isMerge": false
  },
  {
    "hash": "e1ed72eaf7a7f3507024c0fa4ed3a9157585a95b",
    "shortHash": "e1ed72e",
    "committedAt": "2026-07-19T11:40:57+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add mail delivery logs",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "53056cf9ff014148a173eed62e0ac1147e802812",
    "shortHash": "53056cf",
    "committedAt": "2026-07-19T03:41:10Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.81",
    "type": "build",
    "version": "0.2.81",
    "isMerge": false
  },
  {
    "hash": "7ff607007bbd4902f85269d48d6526a1a8134a81",
    "shortHash": "7ff6070",
    "committedAt": "2026-07-19T11:50:12+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: restrict QQ bot rollout users",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "86858a598c99357d39cad4810de02929a42f767b",
    "shortHash": "86858a5",
    "committedAt": "2026-07-19T03:50:25Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.82",
    "type": "build",
    "version": "0.2.82",
    "isMerge": false
  },
  {
    "hash": "ad0d889c2909a4f8ca44df17a05e95b4b69d4fd7",
    "shortHash": "ad0d889",
    "committedAt": "2026-07-19T11:57:35+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: start QQ worker from compiled entry",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "caa82b9525b6aab436d2fc729ed53e968044c33f",
    "shortHash": "caa82b9",
    "committedAt": "2026-07-19T03:57:49Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.83",
    "type": "build",
    "version": "0.2.83",
    "isMerge": false
  },
  {
    "hash": "cf711182c9385761dc7f4c178d1a3825ecb20122",
    "shortHash": "cf71118",
    "committedAt": "2026-07-19T12:54:10+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: accept persisted QQ draft optionals",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "af0b6bf48d8edb64f50f84a6b565e229ff36ca43",
    "shortHash": "af0b6bf",
    "committedAt": "2026-07-19T04:54:23Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.84",
    "type": "build",
    "version": "0.2.84",
    "isMerge": false
  },
  {
    "hash": "9e2bcefd1878154297b084f2371bae570f7861a7",
    "shortHash": "9e2bcef",
    "committedAt": "2026-07-19T13:10:25+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add one-message QQ draft review",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ea80d888b90004c6365450c36eba896bea5b12f0",
    "shortHash": "ea80d88",
    "committedAt": "2026-07-19T05:10:47Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.85",
    "type": "build",
    "version": "0.2.85",
    "isMerge": false
  },
  {
    "hash": "522e130fcc01d708d32a2668dfa146884ca282fa",
    "shortHash": "522e130",
    "committedAt": "2026-07-19T15:53:59+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add QQ bot admin monitoring",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ad40d8c1eaead67522433141d1283afedf5642af",
    "shortHash": "ad40d8c",
    "committedAt": "2026-07-19T07:54:40Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.86",
    "type": "build",
    "version": "0.2.86",
    "isMerge": false
  },
  {
    "hash": "24b69da54db9f22eb5fee6a50f6789da10aabf87",
    "shortHash": "24b69da",
    "committedAt": "2026-07-19T18:25:10+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: expand secure admin operations",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a753aef7bd2c9408cea2e132874f04f2e48380ce",
    "shortHash": "a753aef",
    "committedAt": "2026-07-19T10:25:36Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.87",
    "type": "build",
    "version": "0.2.87",
    "isMerge": false
  },
  {
    "hash": "90aac27915adcd98550dcb5f6f42a21d4614769b",
    "shortHash": "90aac27",
    "committedAt": "2026-07-19T19:56:10+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: detect QQ account disconnects",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ddb754d4dcda6a2fb94ea3385c7156aeb06fb444",
    "shortHash": "ddb754d",
    "committedAt": "2026-07-19T11:56:44Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.88",
    "type": "build",
    "version": "0.2.88",
    "isMerge": false
  },
  {
    "hash": "bbd489f8a361f1a18ff3e7072aefcd3651e84876",
    "shortHash": "bbd489f",
    "committedAt": "2026-07-19T20:49:50+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add bot recovery and DM consent",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "cd7140c231a85737329c2f9bf5915c8b616f1a4e",
    "shortHash": "cd7140c",
    "committedAt": "2026-07-19T12:50:31Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.89",
    "type": "build",
    "version": "0.2.89",
    "isMerge": false
  },
  {
    "hash": "fe9248f324c26073089ae98ef89b300bfc84b5a2",
    "shortHash": "fe9248f",
    "committedAt": "2026-07-19T21:09:37+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: preserve DM consent paragraphs",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "927b75315bb28cbee7ad0ae61a2af116ec814b61",
    "shortHash": "927b753",
    "committedAt": "2026-07-19T13:09:57Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.90",
    "type": "build",
    "version": "0.2.90",
    "isMerge": false
  },
  {
    "hash": "3f1ea91c3feb9320026c4422942c8feb9e50bc14",
    "shortHash": "3f1ea91",
    "committedAt": "2026-07-19T21:59:49+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add chat monitoring controls",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "0f67e393a312db7593f60ee506438c236f44367f",
    "shortHash": "0f67e39",
    "committedAt": "2026-07-19T14:00:35Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.91",
    "type": "build",
    "version": "0.2.91",
    "isMerge": false
  },
  {
    "hash": "ea4870945992c88831b019a7b2c068eb45db06eb",
    "shortHash": "ea48709",
    "committedAt": "2026-07-19T22:51:55+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: improve user search and consent UI",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "b031f1c9f17c76527783d8481ab4c4647dacbd3a",
    "shortHash": "b031f1c",
    "committedAt": "2026-07-19T14:52:26Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.92",
    "type": "build",
    "version": "0.2.92",
    "isMerge": false
  },
  {
    "hash": "a6909726001a9e7316d5174ac93fe84077533160",
    "shortHash": "a690972",
    "committedAt": "2026-07-19T23:57:47+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add QQ bot recovery controls",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "39704a7f531f6a5a426a5ebcd6e6ff7d1c391236",
    "shortHash": "39704a7",
    "committedAt": "2026-07-19T15:58:02Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.93",
    "type": "build",
    "version": "0.2.93",
    "isMerge": false
  },
  {
    "hash": "5847d01664b15517fa46c8631bb3ff6401d3d165",
    "shortHash": "5847d01",
    "committedAt": "2026-07-20T00:31:16+08:00",
    "authorName": "chlink2025",
    "subject": "fix the display issues of like and bookmark",
    "type": "other",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c5579ea74aff4fb605945695c45a887050f6f75d",
    "shortHash": "c5579ea",
    "committedAt": "2026-07-20T00:58:26+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: harden account recovery and mutual aid workflows",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "b56278a223e98a8e05cbfc2f6e62164197b08a8b",
    "shortHash": "b56278a",
    "committedAt": "2026-07-19T16:59:03Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.94",
    "type": "build",
    "version": "0.2.94",
    "isMerge": false
  },
  {
    "hash": "2fb00bdf21727d374da59fda3d77192f921f6e01",
    "shortHash": "2fb00bd",
    "committedAt": "2026-07-20T01:05:59+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: exclude usage consents from registration",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "754ff17575fce09378d1f5eab13ccc72f7cca1cf",
    "shortHash": "754ff17",
    "committedAt": "2026-07-19T17:06:25Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.95",
    "type": "build",
    "version": "0.2.95",
    "isMerge": false
  },
  {
    "hash": "6af918ea3c0d55c7a773d2e757f9fc50c8579e0c",
    "shortHash": "6af918e",
    "committedAt": "2026-07-20T09:15:58+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: simplify invite registration form",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a6ea8d56800112d0562dd2eca18fd8872f870838",
    "shortHash": "a6ea8d5",
    "committedAt": "2026-07-20T09:15:58+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: require login policy consent",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "a7a98ec231411c67983deb0a2a3bd1217152f63f",
    "shortHash": "a7a98ec",
    "committedAt": "2026-07-20T03:07:03Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.96",
    "type": "build",
    "version": "0.2.96",
    "isMerge": false
  },
  {
    "hash": "64b2dd8be7b103ec5ebc8a905e5b71658cfc278d",
    "shortHash": "64b2dd8",
    "committedAt": "2026-07-20T11:47:55+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add SMS auth and profile onboarding",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "588064ff5cac1ba8e372fb04feaa7adedcffc0c2",
    "shortHash": "588064f",
    "committedAt": "2026-07-20T03:57:46Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.97",
    "type": "build",
    "version": "0.2.97",
    "isMerge": false
  },
  {
    "hash": "9779af62ed38d86152a8482d495c3ecebf197e76",
    "shortHash": "9779af6",
    "committedAt": "2026-07-20T12:54:36+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: manage homepage content",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "41c698a2e6519d8fa7c22a2652cf4483968bc5cb",
    "shortHash": "41c698a",
    "committedAt": "2026-07-20T04:54:58Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.98",
    "type": "build",
    "version": "0.2.98",
    "isMerge": false
  },
  {
    "hash": "26674c35ed9a6739bc771faa7ac96e909c1c6085",
    "shortHash": "26674c3",
    "committedAt": "2026-07-20T13:22:52+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: require verified registration",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "8ff3166623e6aabfdc905001218824850858c181",
    "shortHash": "8ff3166",
    "committedAt": "2026-07-20T05:23:13Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.2.99",
    "type": "build",
    "version": "0.2.99",
    "isMerge": false
  },
  {
    "hash": "603192bf1526df4a54610c1ad9b66f0457681caf",
    "shortHash": "603192b",
    "committedAt": "2026-07-20T15:19:47+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add admin changelog",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "b4add6d324034f4f32b4db043550328aa17c0461",
    "shortHash": "b4add6d",
    "committedAt": "2026-07-20T15:19:47+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add announcements and post pinning",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "ae0f89a502b6bed2ba4eda26b677c7b997e13981",
    "shortHash": "ae0f89a",
    "committedAt": "2026-07-20T07:20:15Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.0",
    "type": "build",
    "version": "0.3.0",
    "isMerge": false
  },
  {
    "hash": "9878aeab4f75de2e973aaf070a7568d3dc25408e",
    "shortHash": "9878aea",
    "committedAt": "2026-07-20T15:21:58+08:00",
    "authorName": "zhangli091011",
    "subject": "docs: align changelog version",
    "type": "docs",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "2e1f99ab22e6c14d19b23bbe32f4d439b33d8170",
    "shortHash": "2e1f99a",
    "committedAt": "2026-07-20T07:22:26Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.1",
    "type": "build",
    "version": "0.3.1",
    "isMerge": false
  },
  {
    "hash": "7fb9b79b65e01e955b1596fa0041720237391c5c",
    "shortHash": "7fb9b79",
    "committedAt": "2026-07-20T15:46:18+08:00",
    "authorName": "zhangli091011",
    "subject": "Merge upstream main into pull request",
    "type": "merge",
    "version": null,
    "isMerge": true
  },
  {
    "hash": "9db260eaa30c0ef7df2c6bfbef0fc0edbd6f9b7d",
    "shortHash": "9db260e",
    "committedAt": "2026-07-20T15:46:31+08:00",
    "authorName": "zhangli091011",
    "subject": "test: cover persisted post interactions",
    "type": "test",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "46aacdb06a09db84050ff48d9d9ec71934caf0ef",
    "shortHash": "46aacdb",
    "committedAt": "2026-07-20T07:48:31Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.2",
    "type": "build",
    "version": "0.3.2",
    "isMerge": false
  },
  {
    "hash": "bcc2aaaca4789b4a12af73952f2fcbaf6de43ff6",
    "shortHash": "bcc2aaa",
    "committedAt": "2026-07-20T15:58:11+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: show unread message badges",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c35af2b5891d4c570a45990fe886f52a9e5e74b7",
    "shortHash": "c35af2b",
    "committedAt": "2026-07-20T07:58:51Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.3",
    "type": "build",
    "version": "0.3.3",
    "isMerge": false
  },
  {
    "hash": "93735108ebf700b1cdd4f31ca7730d8a38d733af",
    "shortHash": "9373510",
    "committedAt": "2026-07-20T17:11:10+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add QQ official bot",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "c3537a0faa2d93464b61e1897861478798aae60c",
    "shortHash": "c3537a0",
    "committedAt": "2026-07-20T09:11:30Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.4",
    "type": "build",
    "version": "0.3.4",
    "isMerge": false
  },
  {
    "hash": "84bfb0d4d53004bae8206765a1b86d4872a14c74",
    "shortHash": "84bfb0d",
    "committedAt": "2026-07-20T18:10:37+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: stabilize QQ bot recovery",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "b52e4b91dcf96e0ef3f662da38ff0c7b63d36f1d",
    "shortHash": "b52e4b9",
    "committedAt": "2026-07-20T10:11:01Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.5",
    "type": "build",
    "version": "0.3.5",
    "isMerge": false
  },
  {
    "hash": "3288ecc42a4f30ba070249e269aeed835231bce3",
    "shortHash": "3288ecc",
    "committedAt": "2026-07-20T18:24:28+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: complete mutual aid dispute recovery",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "99082b60e4cc0a7adc29849268555a5573753c85",
    "shortHash": "99082b6",
    "committedAt": "2026-07-20T10:25:09Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.6",
    "type": "build",
    "version": "0.3.6",
    "isMerge": false
  },
  {
    "hash": "b90f76637b5c0d88f629bf57a991084363ac75d4",
    "shortHash": "b90f766",
    "committedAt": "2026-07-20T19:33:32+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add QQ bot verified registration",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "e5fdc10094ecb5bb131930dbfc41aad00554e31f",
    "shortHash": "e5fdc10",
    "committedAt": "2026-07-20T11:34:19Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.7",
    "type": "build",
    "version": "0.3.7",
    "isMerge": false
  },
  {
    "hash": "7b7c30cff68a950b3eac5ffa5ba28b7a4f1dfa5e",
    "shortHash": "7b7c30c",
    "committedAt": "2026-07-20T20:00:10+08:00",
    "authorName": "zhangli091011",
    "subject": "fix: restore password login identifiers",
    "type": "fix",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "357b8a5d85b9626175ca6cc63d8142a2f94866e3",
    "shortHash": "357b8a5",
    "committedAt": "2026-07-20T12:00:33Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.8",
    "type": "build",
    "version": "0.3.8",
    "isMerge": false
  },
  {
    "hash": "6f8090e3998d40c78b4fd48b073e1c665daa4a9b",
    "shortHash": "6f8090e",
    "committedAt": "2026-07-20T21:55:42+08:00",
    "authorName": "zhangli091011",
    "subject": "feat: add identity verification badges",
    "type": "feat",
    "version": null,
    "isMerge": false
  },
  {
    "hash": "218c81c7d58834a83b9d794b49518cfe5be0c1d4",
    "shortHash": "218c81c",
    "committedAt": "2026-07-20T13:56:20Z",
    "authorName": "github-actions[bot]",
    "subject": "build: bump version to v0.3.9",
    "type": "build",
    "version": "0.3.9",
    "isMerge": false
  }
] as const;
